import { InputCustomEvent, IonicModule } from '@ionic/angular';
import { CommonModule } from '@angular/common';
import { AfterViewInit, Component, ElementRef, Input, NgZone, OnDestroy, OnInit, ViewChild } from '@angular/core';
import { ModalController } from '@ionic/angular';
import { FormsModule } from '@angular/forms';

@Component({
  templateUrl: 'search-productModal.page.html',
  standalone: true,
  imports: [
    IonicModule,
    CommonModule,
    FormsModule
  ],
  selector: 'search-product',
  styleUrls: ['search-productModal.page.scss']
})
export class SearchProductModalComponent implements OnInit, AfterViewInit, OnDestroy {

  public searchInput: string = '';
  public currentCategoryList: string[];

  constructor(
    private modalCtrl: ModalController
  ) {
    this.currentCategoryList = fullCategoryList;
  }

  ngOnInit() {
    console.log(`SearchProductModalComponent.constructor: ngOnInit`);
  }

  public ngAfterViewInit(): void {
    console.log(`SearchProductModalComponent.ngAfterViewIn after view init`);
    setTimeout(() => {
      this.resetInput();
    }, 500);
    this.currentCategoryList = fullCategoryList;
    console.log(`SearchProductModalComponent.ngAfterViewIn this current category list: ${JSON.stringify(this.currentCategoryList)}`);
  }

  public ngOnDestroy(): void {
    console.log(`SearchProductModalComponent.ngOnDestroy: destroying view`);
    this.resetInput();
  }

  cancel() {
    return this.modalCtrl.dismiss(null, 'cancel');
  }

  filterList() {
    this.currentCategoryList = fullCategoryList.filter((category) => {
      const match = category.toLocaleLowerCase().match(this.searchInput.toLocaleLowerCase());
      const didMatch = match && Number(match.index) > -1;
      console.log(`SearchProductModalComponent.filterList: checking if ${category} matches ${this.searchInput}`);
      console.log(`SearchProductModalComponent.filterList: did match: ${didMatch}`);
      return didMatch;
    });
  }

  async search(category: string) {
    console.log(`SearchProductModalComponent.search: used the text input: ${this.searchInput}`);
    console.log(`SearchProductModalComponent.search: start search with input: ${category}`);
    return this.modalCtrl.dismiss(category, 'confirm');
  }

  private async resetInput(): Promise<void> {
    this.searchInput = '';
  }
}

const fullCategoryList = [
  "Plant-based foods and beverages",
  "Plant-based foods",
  "Snacks",
  "Sweet snacks",
  "Beverages",
  "Dairies",
  "Cereals and potatoes",
  "Meats and their products",
  "Fermented foods",
  "Fermented milk products",
  "Fruits and vegetables based foods",
  "Condiments",
  "Meats",
  "Desserts",
  "Biscuits and cakes",
  "Meals",
  "Cereals and their products",
  "Spreads",
  "Sauces",
  "Cheeses",
  "Groceries",
  "Confectioneries",
  "Frozen foods",
  "Breakfasts",
  "Prepared meats",
  "Plant-based beverages",
  "Vegetables based foods",
  "Cocoa and its products",
  "Canned foods",
  "Seafood",
  "Sweet spreads",
  "Fruits based foods",
  "Biscuits",
  "Dairy desserts",
  "Breads",
  "Plant-based spreads",
  "Fats",
  "Fermented dairy desserts",
  "Fishes and their products",
  "Salty snacks",
  "Fishes",
  "Pastas",
  "Alcoholic beverages",
  "Yogurts",
  "Sweeteners",
  "Frozen desserts",
  "Legumes and their products",
  "Seeds",
  "Vegetable fats",
  "Poultries",
  "Appetizers",
  "Cakes",
  "Canned plant-based foods",
  "Chocolates",
  "Farming products",
  "Nuts and their products",
  "Vegetables",
  "Fruit-based beverages",
  "Dried products",
  "Vegetable oils",
  "Fatty fishes",
  "Juices and nectars",
  "Beverages and beverages preparations",
  "Dietary supplements",
  "Hot beverages",
  "Breakfast cereals",
  "Chocolate candies",
  "Bee products",
  "Fruit and vegetable preserves",
  "Carbonated drinks",
  "Legumes",
  "Chicken and its products",
  "Honeys",
  "Olive tree products",
  "Cow cheeses",
  "Candies",
  "Chickens",
  "Fruits",
  "Chips and fries",
  "Sodas",
  "Ice creams and sorbets",
  "Nuts",
  "Jams",
  "Salted spreads",
  "Fruit juices",
  "Crisps",
  "Hams",
  "Milks",
  "Soups",
  "Canned vegetables",
  "Cereal grains",
  "Sausages",
  "Dairy substitutes",
  "Teas",
  "Wines",
  "Dried plant-based foods",
  "Olive oils",
  "Waters",
  "Meals with meat",
  "Pasta dishes",
  "French cheeses",
  "Pastries",
  "Ice creams",
  "Pizzas pies and quiches",
  "Sweet pastries and pies",
  "Viennoiseries",
  "Bodybuilding supplements",
  "Coffees",
  "Sweetened beverages",
  "Bars",
  "Extra-virgin olive oils",
  "Dried products to be rehydrated",
  "Italian cheeses",
  "Canned fishes",
  "Dried fruits",
  "Meat alternatives",
  "Dark chocolates",
  "Milk substitutes",
  "Tomatoes and their products",
  "Beers",
  "Tomato sauces",
  "Pizzas",
  "Dips",
  "Meat preparations",
  "Pork and its products",
  "Spices",
  "Virgin olive oils",
  "Pork",
  "Legume seeds",
  "Cured sausages",
  "Pickles",
  "Cooking helpers",
  "Fresh foods",
  "Syrups",
  "Pulses",
  "Rices",
  "Plant-based milk alternatives",
  "Plant-based pickles",
  "Frozen plant-based foods",
  "Bonbons",
  "Tunas",
  "Festive foods",
  "Crackers",
  "White hams",
  "Sandwiches",
  "Salted-snacks",
  "Salmons",
  "Potato crisps",
  "Canned legumes",
  "Dairy drinks",
  "Chocolate biscuits",
  "Spreadable fats",
  "Unsweetened beverages",
  "Fermented dairy desserts with fruits",
  "Tea-based beverages",
  "Frozen vegetables",
  "Flours",
  "Hard cheeses",
  "Dry pastas",
  "Brioches",
  "Prepared salads",
  "Meat analogues",
  "Oilseed purees",
  "Milk chocolates",
  "Beef and its products",
  "Breaded products",
  "Fish fillets",
  "Stuffed pastas",
  "Non food products",
  "Fermented drinks",
  "Berry jams",
  "Herbal teas",
  "Mueslis",
  "Noodles",
  "Cereal pastas",
  "Eggs",
  "Fruit yogurts",
  "Fish and meat and eggs",
  "Smoked fishes",
  "Chicken breasts",
  "Culinary plants",
  "Beef",
  "Durum wheat pasta",
  "Compotes",
  "Uncooked pressed cheeses",
  "Christmas foods and drinks",
  "Spring waters",
  "Tomatoes",
  "Artificially sweetened beverages",
  "Animal fats",
  "Protein powders",
  "Turkey and its products",
  "Vinegars",
  "Poultry meals",
  "Canned meals",
  "Mustards",
  "Canned tunas",
  "Fish preparations",
  "Olives",
  "Special breads",
  "Turkeys",
  "Milkfat",
  "Dairy-spread",
  "Butters",
  "Prepared vegetables",
  "Pastry helpers",
  "Canned fruits",
  "Non-alcoholic beverages",
  "Open Beauty Facts",
  "Cured hams",
  "Pâtes à tartiner",
  "Instant beverages",
  "Flakes",
  "Cereal flours",
  "Legume butters",
  "Smoked salmons",
  "Fresh plant-based foods",
  "Peanut butters",
  "Mineral waters",
  "Baby foods",
  "Salads",
  "Dessert mixes",
  "Vegetable soups",
  "Wines from France",
  "Sugars",
  "Cereal flakes",
  "Mayonnaises",
  "Creams",
  "Iced teas",
  "Frozen seafood",
  "Extruded cereals",
  "Food additives",
  "Ice cream tubs",
  "Ketchup",
  "Specific products",
  "Salad dressings",
  "Pies",
  "Apple compotes",
  "Fruit nectars",
  "Terrines",
  "Flavoured syrups",
  "Fermented milk drinks",
  "Stretched-curd cheeses",
  "Charcuteries cuites",
  "Charcuteries diverses",
  "Simple syrups",
  "Sliced breads",
  "Dried hams",
  "Protein bars",
  "Canned common beans",
  "Leaf vegetables",
  "Tropical fruits",
  "Squeezed-juices",
  "Cereal bars",
  "Plain fermented dairy desserts",
  "Microwave meals",
  "Meals with fish",
  "Pasta sauces",
  "Foies gras",
  "Fresh vegetables",
  "Rillettes",
  "Corn chips",
  "Vegetable rods",
  "Orange juices",
  "Soft cheeses",
  "Christmas sweets",
  "Nut butters",
  "Meals with chicken",
  "Gummi candies",
  "Apple juices",
  "Baking Mixes",
  "Products for specific diets",
  "Rice dishes",
  "Ducks",
  "Long grain rices",
  "Sweet pies",
  "French sausages",
  "Chocolate cakes",
  "Greek-style yogurts",
  "Pestos",
  "Hummus",
  "Berries",
  "Chicken preparations",
  "Cream cheeses",
  "Cake mixes",
  "Mozzarella",
  "Foies gras from ducks",
  "Mushrooms and their products",
  "Dehydrated beverages",
  "Semi-skimmed milks",
  "Energy drinks",
  "Common beans",
  "Pasteurized cheeses",
  "Panettone",
  "Canned soups",
  "Comté",
  "Peanuts",
  "Chocolate spreads",
  "Shortbread cookies",
  "Soft cheeses with bloomy rind",
  "Cooked poultries",
  "Capsules",
  "Homogenized milks",
  "Salts",
  "Salami",
  "Sardines",
  "Sheep's-milk cheeses",
  "Colas",
  "Sunflower seeds and their products",
  "Broths",
  "Flower honeys",
  "Goat cheeses",
  "Frozen ready-made meals",
  "Almonds",
  "Whole milks",
  "Wheat flours",
  "Beef dishes",
  "Crustaceans",
  "Italian meat products",
  "Canned sardines",
  "Pickled vegetables",
  "Emmentaler",
  "Cocoa and chocolate powders",
  "Aromatic plants",
  "Flatbreads",
  "Red wines",
  "Baking-decorations",
  "Products without gluten",
  "Tunas in oil",
  "Puffed cereal cakes",
  "Madeleines",
  "Hazelnut spreads",
  "Mushrooms",
  "Coffee capsules",
  "Wafers",
  "UHT Milks",
  "Spaghetti",
  "Strawberry jams",
  "Chicken eggs",
  "Turkey cutlets",
  "Turrón",
  "Breadsticks",
  "Instant noodles",
  "Chewing gum",
  "Green teas",
  "Cheeses from the United Kingdom",
  "Ravioli",
  "Chocolate cereals",
  "Shelled nuts",
  "Mixed vegetables",
  "Distilled beverages",
  "Plain yogurts",
  "Dry sausages",
  "Non-dairy desserts",
  "Grated cheese",
  "Aromatic rices",
  "Cheeses from England",
  "Mollusc",
  "Cashew nuts",
  "Hard liquors",
  "Crêpes and galettes",
  "Natural mineral waters",
  "Frozen pizzas and pies",
  "Meal sauces",
  "Country specific beers",
  "Pâté",
  "Tea bags",
  "Indica rices",
  "Cereal-based drinks",
  "Shrimps",
  "Green olives",
  "Barbecue sauces",
  "Popcorn",
  "Cheddar cheese",
  "White breads",
  "Dry biscuits",
  "Fresh fruits",
  "Instant coffees",
  "Bars-covered-with-chocolate",
  "Lentils",
  "Cocoa and hazelnuts spreads",
  "Cereals with fruits",
  "Filled biscuits",
  "Carbonated waters",
  "Rolled flakes",
  "Cheeses of the Netherlands",
  "Frozen meats",
  "Herbs",
  "Kombuchas",
  "Puddings",
  "Chocolate desserts",
  "Diet beverages",
  "Plant-based creams",
  "Beverage preparations",
  "Spanish meat products",
  "Dates",
  "Frozen pizzas",
  "Easter food",
  "Margarines",
  "Drinkable yogurts",
  "Pie dough",
  "Fruit and fruit seed oils",
  "Multifruit juices",
  "Labeled-cheeses",
  "Soy sauces",
  "Extruded flakes",
  "Raw-cured-ham",
  "Refrigerated foods",
  "Plant-based creams for cooking",
  "Aoc-cheeses",
  "Biscuits and crackers",
  "Gouda",
  "Flavoured milks",
  "Chicken thighs",
  "Sorbets",
  "Fresh pasta",
  "Sardines in oil",
  "Serrano ham",
  "Beef preparations",
  "Hot sauces",
  "Poultry hams",
  "Cooked chicken",
  "Gingerbreads",
  "Flavoured potato crisps",
  "Wholemeal breads",
  "Blue-veined cheeses",
  "Pickled cucumbers",
  "Cheese spreads",
  "Onions and their products",
  "Rolled oats",
  "Mackerels",
  "Breaded chicken",
  "Baguettes",
  "Balsamic vinegars",
  "Potatoes",
  "Asparagus",
  "Whole foies gras",
  "Vegetarian pizzas",
  "Cream soups",
  "Pork meals",
  "Drop cookies",
  "Eaux de vie",
  "Gnocchi",
  "Dried meats",
  "Apricot jams",
  "Potted meats",
  "Chickpeas",
  "Doughnuts",
  "Tuna in olive oil",
  "Lean fishes",
  "Sliced cheeses",
  "Dried meals",
  "Carrots",
  "Fruit juices from concentrate",
  "Coconut milks and creams",
  "Potato crisps in sunflower oil",
  "Diet sodas",
  "Puffed rice cakes",
  "Fruits in syrup",
  "Mueslis with fruits",
  "Lagers",
  "Basmati rices",
  "Roasted nuts",
  "Mountain products",
  "Lemonade",
  "Waffles",
  "Offals",
  "Coconut oils",
  "Steaks",
  "Gherkins",
  "Fromages blancs",
  "Parmigiano-Reggiano",
  "Mackerel fillets",
  "Grana Padano",
  "Non-dairy fermented foods",
  "Nut-based drinks",
  "Croissants",
  "Fruit sodas",
  "Fresh meals",
  "Legume-based drinks",
  "Ales",
  "Creamy puddings",
  "Soy-based drinks",
  "Vegetarian patties",
  "Oat-based drinks",
  "Sugar-free chewing gum",
  "Fresh cheeses",
  "Non-dairy yogurts",
  "Green pestos",
  "Non-alcoholic beers",
  "Cow milk yogurts",
  "Artisan products",
  "Nougats",
  "Plant-based meals",
  "Prepared lasagne",
  "Stuffed wafers",
  "Cream of vegetable soups",
  "Tofu",
  "Reheatable soups",
  "Green beans",
  "Smoothies",
  "Breaded fish",
  "Toasts",
  "Mussels",
  "Fish rillettes",
  "Quarks",
  "Chipolatas",
  "Ice cream bars",
  "Corn flakes",
  "Wheat breads",
  "Potato gnocchi",
  "Maple syrups",
  "Creamer",
  "Flavoured fermented dairy desserts",
  "Sunflower oils",
  "Whole foies gras from ducks",
  "Sunflower seeds",
  "Chorizo",
  "Beef steaks",
  "Vegetable-based foods and beverages",
  "Cow milks",
  "Garlic and their products",
  "White chocolates",
  "Filled chocolates",
  "Poultry sausages",
  "White wines",
  "Dehydrated broths",
  "Chocolates with hazelnuts",
  "Spice Mix",
  "Chocolate eggs",
  "Bacon",
  "Walnuts",
  "Almond-based drinks",
  "Chocolate molds",
  "Cereal semolinas",
  "Pistachios",
  "Green peas",
  "Peppers",
  "Duck breasts",
  "Purées",
  "Canned tomatoes",
  "Flavoured yogurts",
  "Acacia honeys",
  "Flavored waters",
  "Chocolate croissant",
  "Citrus jams",
  "Refrigerated meals",
  "Egg pastas",
  "Dehydrated soups",
  "Tortellini",
  "Pork Pâtés",
  "Fresh meats",
  "Easter eggs",
  "Boudins",
  "Coffee drinks",
  "Apples",
  "Pork roasts",
  "Pumpkin and Squash plant products",
  "Poultry nuggets",
  "Raspberry jams",
  "Ground steaks",
  "Chocolate powders",
  "Muffins",
  "Fermented creams",
  "Salted nuts",
  "Raisins",
  "Citrus",
  "Cocoa powders",
  "Bakery products",
  "Chocolate chip cookies",
  "Chocolate milks",
  "Rusks",
  "Frozen fried potatoes",
  "Unpasteurised cheeses",
  "Frozen fishes",
  "Tripe dishes",
  "Vegetable-based beverages",
  "Penne",
  "Ground beef steaks",
  "Aiguillettes de poulet",
  "Quinoa",
  "Hamburgers",
  "Hamburger buns",
  "Crêpes",
  "White meat rillettes",
  "French blue-veined cheeses",
  "Balsamic vinegars of Modena",
  "Bananas",
  "Stews",
  "Vegetable juices",
  "Chicken nuggets",
  "Assorted chocolate candies",
  "Poultry rillettes",
  "Ciders",
  "Potato preparations",
  "Black teas",
  "Ground coffees",
  "Salted pies",
  "Free-range chicken eggs",
  "Cooked chicken breast slices",
  "Preparations-made-from-fish-meat",
  "Roasted peanuts",
  "Camemberts",
  "Flavored teas",
  "Artisanal spirits",
  "Dehydrated sauces",
  "Artichokes",
  "Honeys from France",
  "Sardines in olive oil",
  "Marmalades",
  "Pitted olives",
  "Skimmed milks",
  "Rapeseed oils",
  "Sweet Fritters",
  "Country terrines",
  "Sugar substitutes",
  "Marshmallows",
  "Caramels",
  "Wines from Italy",
  "Stirred yogurts",
  "Tapenades",
  "Duck dishes",
  "Mexican-dinner-mixes",
  "Brownies",
  "Applesauces",
  "Dried apricots",
  "Mountain cheeses",
  "Cods",
  "Canned meats",
  "Sushi and Maki",
  "Squeezed orange juices",
  "Fermented vegetables",
  "Tartlets",
  "Canned cereals",
  "Craft beers",
  "Rice puddings",
  "Canned corn",
  "Cereal oils",
  "Fresh eggs",
  "Bifidus yogurts",
  "Spirulina",
  "Skyrs",
  "Macarons",
  "Diet cola soft drink",
  "Blueberries",
  "Trouts",
  "Garlic",
  "White beans",
  "Sparkling wines",
  "Liqueurs",
  "Anchovy",
  "Cheese pizzas",
  "Kefir",
  "Pale ales",
  "Onions",
  "Squeezed apple juices",
  "Dried prunes",
  "Tabbouleh",
  "Baby milks",
  "Coffee beans",
  "White rices",
  "Fries",
  "Buffalo cheeses",
  "Turkey preparations",
  "Mueslis with chocolate",
  "White asparagus",
  "Gratins",
  "Chocolates with almonds",
  "French emmentaler",
  "Sea salts",
  "Strawberries",
  "Stuffed olives",
  "Sweet peppers",
  "Salmon fillets",
  "Black olives",
  "Red beans",
  "Pineapple",
  "Sweet mousses",
  "Black pudding",
  "Sauerkrauts",
  "Vinaigrettes",
  "Sushis",
  "Dijon mustards",
  "Spinachs",
  "Common wheat flours",
  "Porridge",
  "Ice cream cones",
  "Fish soups",
  "Mixed fruit jams",
  "Bean dishes",
  "Cordons bleus",
  "Wraps",
  "Tomme cheese from cow's milk",
  "Chutneys",
  "Nespresso-compatible coffee capsules",
  "Pumpkin seeds and their products",
  "Penne rigate",
  "Cheeses from Switzerland",
  "Ground meat preparations",
  "Lamb meat",
  "Corn",
  "Wheat flatbreads",
  "Allumettes de porc",
  "Sweetened yogurts",
  "Herring",
  "Bilberries jams",
  "Block of foie gras",
  "Cold soups",
  "Wine vinegars",
  "Poultry terrines",
  "Cherry jams",
  "Canned mussels",
  "Greek cheeses",
  "Country-style Pâtés",
  "Milk chocolate biscuits",
  "Dried vegetables",
  "Wheat semolinas",
  "Anchovy fillets",
  "Seaweeds and their products",
  "Canned green beans",
  "Chia",
  "Chestnut spreads",
  "Potato dishes",
  "Buffalo mozzarella",
  "Vitamins",
  "Reblochon",
  "Unsalted butters",
  "Salty snacks made from potato",
  "French beers",
  "Snacks and desserts for babies",
  "Risottos",
  "Bagel breads",
  "Whole milk yogurts",
  "Cider vinegars",
  "Champignon mushrooms",
  "Vegetarian balls",
  "Tuna-in-brine",
  "Meat lasagnas",
  "Chocolate covered nuts",
  "Dairy Mousses",
  "Processed cheese",
  "Puff pastry meals",
  "Cassoulets",
  "Frozen plant-based foods mixes",
  "Tomato pastes",
  "Flavors",
  "Canned sweet corn",
  "Guacamoles",
  "Surimi",
  "Vegetarian sausages",
  "Puffed salty snacks",
  "Boudins blancs",
  "Energy bars",
  "Feta",
  "Smoked salmons from farming",
  "Bolognese lasagne",
  "Leaf salads",
  "Lardons",
  "Dried tomatoes",
  "Fruit pastes",
  "Lollipops",
  "Taralli",
  "Bries",
  "Smoked trouts",
  "Almond butters",
  "Hazelnuts",
  "Vegetable broths",
  "Canned peas",
  "Rye breads",
  "Frozen fruits",
  "Cheese substitutes",
  "Main meals for babies",
  "Beef jerkies",
  "Agave syrups",
  "Smoked sausages",
  "Meat-based sauces",
  "Colomba",
  "Tomato purées",
  "Yule log",
  "Savory semolina dishes",
  "Artichoke hearts",
  "Orange jams",
  "Bordeaux wines",
  "Cottage cheeses",
  "Dessert sauces",
  "Shelled almonds",
  "Nut confectioneries",
  "Strawberry yogurts",
  "Cucurbitacea seeds",
  "Breaded meat cutlets",
  "Pumpkin seeds",
  "Fruit jellies",
  "Buns",
  "Quiches",
  "Sour creams",
  "Tomato Ketchup",
  "Dry durum wheat pasta",
  "Nems",
  "Dried mixed fruits",
  "Advent calendars",
  "Durum wheat semolinas",
  "Petit-Beurre",
  "Black peppers",
  "Canned mushrooms",
  "Pasta salads",
  "Chocolate truffles",
  "Mashed potatoes",
  "Nut oils",
  "Vanilla yogurt",
  "Snacks-sucres",
  "Sautéed black pudding",
  "Bouillon cubes",
  "Melted cheese",
  "Crispbreads",
  "Gazpacho",
  "Chocolate mousses",
  "Marzipan",
  "Fruit tarts",
  "Chili peppers",
  "Meat-based pasta sauces",
  "Sheep milk yogurts",
  "Croutons",
  "Low-fat yogurts",
  "Decaffeinated coffees",
  "Walnut kernels",
  "Evaporated milks",
  "Galettes",
  "Duck terrines",
  "Lactose-free milk",
  "Margherita Pizza",
  "Rosé wines",
  "Sandwiches filled with cold cuts",
  "Gluten-free pasta",
  "Figs jams",
  "Lemon juice",
  "Puffed grains",
  "Protein shakes",
  "Half-salted butter",
  "Grated emmentaler",
  "Mussels with escabeche",
  "Grapes",
  "Cheesecakes",
  "Fried tomato sauces",
  "Duck rillettes",
  "Pretzel",
  "Puffed cereals",
  "Pizza dough",
  "Chestnut honey",
  "Peeled tomatoes",
  "Roasted pistachios",
  "Tagliatelle",
  "Poultry sandwiches",
  "Refrigerated creamy puddings",
  "King cakes",
  "Potato salads",
  "Tunas in sunflower oil",
  "Brown rices",
  "Green pitted olives",
  "Pineapple juices",
  "Pasta stuffed with meat",
  "Raspberries",
  "Albacore",
  "Raclette",
  "Nut bars",
  "Apple pies",
  "Curry pastes",
  "Filled milk chocolates",
  "Milk chocolates with hazelnuts",
  "Canned chickpeas",
  "Lentil dishes",
  "Soy milk yogurts",
  "Jasmine rice",
  "Kiwifruits",
  "Dried cranberries",
  "Almond turrón",
  "Pandoro",
  "Grape juices",
  "Frozen legumes",
  "Cooked turkey breast slices",
  "Wholemeal sliced breads",
  "Beet",
  "Pitas",
  "Cane sugar",
  "Frozen fries",
  "Broccoli",
  "Green stuffed olives",
  "Champagnes",
  "Soft cheeses with washed rind",
  "jambons-cuits-a-l-ancienne",
  "Meat patties",
  "Bolognese sauces",
  "French fruits",
  "Food decorations",
  "Salads with fish",
  "Grated carrots",
  "Fusilli",
  "Biscuit with a chocolate bar covering",
  "Tartlet biscuits with fruit preparation",
  "Chicken sandwiches",
  "Pound Cake",
  "Ground dried aromatic plants",
  "Carbonated mineral waters",
  "Wheat beers",
  "From 6 months",
  "Chips",
  "Light margarines",
  "Lavender honeys",
  "Ice cream log",
  "Morbier",
  "Frozen cakes and pastries",
  "taralli",
  "Pork ribs",
  "Flax seeds",
  "Carbonated natural mineral waters",
  "Mozzarella di Bufala Campana",
  "Pasteurised milks",
  "Durum wheat spaghetti",
  "Groats",
  "Chocolate cereal bars",
  "Ginger",
  "Fish eggs",
  "Tomato juices",
  "Arrabbiata sauces",
  "Canned asparagus",
  "Tuna salads",
  "Pruneaux d'Agen",
  "Roquefort cheeses",
  "Savory mousses",
  "Bread crumbs",
  "Butter croissants",
  "Breaded turkey",
  "Meat ravioli",
  "Flans",
  "Fresh milks",
  "Ice cream sandwiches",
  "Tuna fillets",
  "Fruit confectioneries",
  "Falafels",
  "Filled cereals",
  "Fresh tomatoes",
  "Pancake mixes",
  "Coconuts",
  "Cinnamon",
  "Chicken cutlets",
  "Rice-based drinks",
  "Fruit teas",
  "Licensed products",
  "Cereal butters",
  "Veal meat",
  "Burrata",
  "Gorgonzolas",
  "Potato gratin",
  "Rices for risotto",
  "Ratatouille",
  "Ricotta",
  "Mimolette cheese",
  "Coconut waters",
  "Tahini",
  "Whisky",
  "Puffed corn cakes",
  "Dried bananas",
  "Glazes with vinegar",
  "Pflanzliche-lebensmittel-und-getranke",
  "Danish cheeses",
  "Cow camemberts",
  "Lettuces",
  "Puff pastry sheets",
  "Gummy bears",
  "Vanilla",
  "Pork sausages",
  "Rums",
  "Chocolate creamy puddings",
  "Herbal teas in tea bags",
  "Mandarin oranges",
  "Industrial cheese",
  "Canned peas and carrots",
  "Chicken drumsticks",
  "Fromages blancs natures",
  "Plant-based pâtés",
  "Japonica rices",
  "Gluten-free breads",
  "Red pestos",
  "Himalaya salts",
  "Baked beans in tomato sauce",
  "Chocolate covered fruits",
  "Plum jams",
  "Chicken sausages",
  "Rillettes de viande rouge",
  "Bread coverings",
  "Ice pops",
  "Peach jams",
  "Sweet cream butters",
  "Squeezed multifruit juices",
  "Tiramisu",
  "Unfermented creams",
  "Tonic water",
  "German sausages",
  "Tonic water",
  "Brown sugars",
  "Prawns",
  "Cherry tomatoes",
  "Salmon steaks",
  "Candy chocolate bars",
  "Chicken wings",
  "Sesame oils",
  "Chocolate rabbits",
  "Curry sauces",
  "Fruit chutneys",
  "Dark chocolates with almonds",
  "Fruit cakes",
  "Mochi",
  "Paprika",
  "Breaded turkey cutlets",
  "Mortadella",
  "Rosette dry sausage",
  "Tuna chunks",
  "Cold starters",
  "Honeys from the mountains",
  "Céréales préparées",
  "Green lentils",
  "Pains de tradition française",
  "Pork filet mignon",
  "Beers from Germany",
  "Smoked lardons",
  "Cod fillets",
  "Mascarpone",
  "Oat",
  "Nut flours",
  "Herbal tea blends",
  "Cod brandade",
  "Wild salmons",
  "Frozen mixed vegetables",
  "Taramasalata",
  "Milk bread rolls",
  "Ice cream bars coated with chocolate",
  "Tropical tunas",
  "Souris d'agneau",
  "Chocolate madeleines",
  "Frozen berries",
  "Flaky biscuits",
  "Ham sandwiches",
  "Cut",
  "Pork rillettes",
  "Food colorings",
  "Wheats",
  "Tortelloni",
  "Sardines in tomato sauce",
  "Oatmeal cookies",
  "Havarti",
  "Dark chocolate biscuits",
  "Tomato sauces with basil",
  "Sesame",
  "Strasbourg sausages",
  "Hot dog buns",
  "Durum wheat semolinas for couscous",
  "Orange juices from concentrate",
  "Dried figs",
  "Pancakes",
  "Deglet Noor dates",
  "Apricot nectars",
  "Assorted chocolates",
  "Tinned Mackerels",
  "Sultana raisins",
  "Canned champignon mushrooms",
  "Meal replacements",
  "Fresh meat preparations",
  "Spanish cheeses",
  "Peaches",
  "Fish fingers",
  "Plant-based ice creams",
  "Skewers",
  "Meals with salmon",
  "Quenelles",
  "Vanilla ice cream tubs",
  "Vegetable salads",
  "Pollocks",
  "Compotes to drink",
  "Sprouts",
  "Pflanzliche-lebensmittel",
  "Extruded crispbreads",
  "Coleslaw",
  "UHT Creams",
  "White Basmati rices",
  "Chocolate turrón",
  "Côtes du Rhône",
  "Whole chickens",
  "Fruits cereal bars",
  "Faiselles",
  "Tropical fruit jams",
  "Meat spreads",
  "Salted butters",
  "Bresaola",
  "Multifruit nectars",
  "Ground beef preparations",
  "Chocolates with sweeteners",
  "Beef ravioli",
  "Beef ravioli",
  "Toasted bread rolls",
  "Eclairs",
  "Dry sausage pure pork",
  "Pork belly",
  "Strained tomatoes",
  "Peaches in syrup",
  "Black tapenades",
  "Yellowfin tunas",
  "Piadina",
  "Salted peanuts",
  "Turkey breasts",
  "Liquorice candies",
  "Dried mushrooms",
  "Fruit salads",
  "Rabbit meat",
  "Stracchino",
  "Fish sandwiches",
  "Miels crémeux",
  "Marinated anchovy fillets",
  "Cantucci",
  "Cabbages",
  "Whipped creams",
  "Aloe Vera drinks",
  "Orange soft drinks",
  "poulets-fermiers",
  "Citrus honeys",
  "Honey candies",
  "Shortbread cookies from Brittany",
  "Aliments-et-boissons-a-base-de-vegetaux",
  "Snails",
  "Tzatzikis",
  "Tabletop sweeteners",
  "Десерт",
  "Melons",
  "Sprinkles",
  "Plain buckwheat crepes",
  "Getranke",
  "Grenadine",
  "Open pies",
  "Coquillettes",
  "Red lentils",
  "Tuna rillettes",
  "Pinto beans",
  "White wine vinegars",
  "Soft cheese with a natural rind",
  "Pickled gherkins",
  "Palets",
  "Vegetarian sauces",
  "Filled cakes",
  "Dark chocolates with hazelnuts",
  "Arômes pâtisserie",
  "Pepperoni pizzas",
  "Vodka",
  "Pâté in crust",
  "Stuffing",
  "Instant mashed potatoes",
  "Open Products Facts",
  "Curry powder",
  "Canned peppers",
  "Seitan",
  "Short grain rices",
  "Avocados",
  "Chocolate sandwich cookies",
  "Picos de pan",
  "Mint syrups",
  "Chinese noodles",
  "Mixed herbs",
  "Filled croissants",
  "Ground dried vegetables",
  "Vegetarian nuggets",
  "Black beans",
  "Pan-fried dishes",
  "fuet",
  "Egg noodles",
  "Apple nectars",
  "Prepared couscous",
  "Filled dark chocolates",
  "Paella",
  "Caramel chocolates",
  "Instant noodle soups",
  "Fondants",
  "Liver Pâtés",
  "Ground peppers",
  "Premixed alcoholic beverages",
  "Artificial sugar substitutes",
  "Cooked vegetables",
  "Pasta stuffed with cheese",
  "Cheese sandwiches",
  "Whole olives",
  "Herring fillets",
  "Strawberry syrups",
  "Peach nectars",
  "Meat balls",
  "Milk jams",
  "Filets de poulet rotis",
  "Dairy chocolate desserts",
  "Pre-baked breads",
  "Whole durum wheat pasta",
  "Oils",
  "Filets de poulet rotis",
  "Chili con carne",
  "Walnut oils",
  "Dehydrated vegetable bouillons",
  "Instant pasta",
  "Apple juices from concentrate",
  "Chocolate biscuity bars",
  "Speculoos",
  "Rigatoni",
  "Prepared rices",
  "Cantal",
  "Salted popcorn",
  "Marinated anchovy fillets with vegetable oil",
  "Unrefined salts",
  "Susser-snack",
  "Spanish omelettes",
  "Marshmallows coated with chocolate",
  "Biscuits-et-gateaux",
  "Milk chocolate bar",
  "Barn chicken eggs",
  "Almond meal",
  "Turmeric",
  "Dragées",
  "Cinnamon powder",
  "Fruits coulis",
  "Toulouse sausages",
  "Mashed vegetables",
  "Peas",
  "Edam",
  "Carrot salads",
  "Duck confit",
  "Couscous",
  "Veal meat dishes",
  "Palmiers",
  "Chocolate covered peanuts",
  "Soy desserts",
  "Meat-products",
  "Orange nectars",
  "Turkish delight",
  "Salted butter caramels",
  "Wheat groats",
  "Apple turnovers",
  "Filled crêpes",
  "Multigrain sliced breads",
  "Brioches tressées",
  "Sauerkraut with garnish",
  "Onion chutneys",
  "Young Goudas",
  "Arabica coffees",
  "Fresh mushrooms",
  "Flavored sparkling waters",
  "Petits suisses",
  "Crunchy mueslis",
  "Eggplant caviar",
  "Hard candies",
  "Breaded cheeses",
  "Sardines in sunflower oil",
  "Liver-sausages",
  "Boissons",
  "Mixed berry jams",
  "Yeast",
  "Bulgur",
  "Frozen spinachs",
  "Fresh apples",
  "Seasoned grated carrots",
  "Chicken wraps",
  "Chocolate ice cream tubs",
  "Puffed salty snacks made from maize",
  "Forest honeys",
  "Salted pistachios",
  "Dried goji",
  "Jelly beans",
  "Granulated sugars",
  "Canned artichokes",
  "Dark chocolate bar",
  "Plantain-chips",
  "Crunchy peanut butters",
  "Chocolate stuffed wafers",
  "Rosemary honeys",
  "Lorraine quiche",
  "Breads with raisins",
  "Garlic sausage",
  "Semi-preserved foods",
  "Pasta stuffed with vegetables",
  "Cherries",
  "Honey-based preparations",
  "Four Cheese Pizza",
  "Blackberry jams",
  "Cauliflowers",
  "Peppercorns",
  "Mochi ice cream",
  "Energy drink with sugar",
  "Fleurs de sel",
  "Tartare sauces",
  "Fruit smoothies",
  "Fleurs de sel",
  "Cannelloni",
  "Meringues",
  "Blueberry yogurts",
  "Salmon Rillettes",
  "Salted cashews",
  "Corn semolinas",
  "Belgian beers",
  "Mint teas",
  "Calamari",
  "Prepared potatoes",
  "Jelly desserts",
  "Vegetables macedoines",
  "Acid gummy candies",
  "Garlic powder",
  "Salted chocolates",
  "Dried coconut",
  "Fruit stirred yogurts",
  "tonno-all-olio-d-oliva",
  "Jaffa cakes",
  "Shortbread",
  "Aiolis",
  "Black pitted olives",
  "Brussels sprouts",
  "Grilled almonds",
  "Chitterling sausage",
  "Teriyaki sauces",
  "Cancoillottes",
  "Chamomile",
  "Imbiss",
  "Pine nuts",
  "Fruit tartlets",
  "Linden honeys",
  "Oranges",
  "French salts",
  "Fruit and milk beverages",
  "Grapefruit juices",
  "Variety packs",
  "Smoked cured hams",
  "Multifruit juices from concentrate",
  "Fresh ground steaks",
  "Pear applesauces",
  "Creamy almond turrón",
  "Pizza sauces",
  "Sweet apples",
  "Flavored black teas",
  "Macaroni and cheese",
  "Calissons",
  "Flavoured chocolates",
  "Chocolate covered almonds",
  "Yellow mustards",
  "Mangoes",
  "Amber beers",
  "Harissa sauces",
  "Meat skewers",
  "Smoked bacon",
  "Grilling cheeses",
  "Breton cakes",
  "Beef broth",
  "Products with reduced salt",
  "Almond cookies",
  "Pizza with ham and cheese",
  "Pollock fillets",
  "Gluten-free biscuits",
  "Marrons glacés",
  "Duck fillets",
  "Pure butter brioche",
  "Cereals with nuts",
  "Orange blossom honeys",
  "Eastern tabbouleh",
  "Cream puff",
  "Mixtures of herbs and spices",
  "Vanilla extract",
  "Vegetable sauces",
  "Meat of the grisons",
  "Dry egg pastas",
  "Aliments-d-origine-vegetale",
  "Canned herrings",
  "Duck mousse",
  "produits-labellises",
  "Shrimps tails",
  "Cheese ravioli",
  "Hollow chocolate eggs",
  "Infant formulas",
  "ESL milks",
  "Light mayonnaises",
  "Sausages with lentils",
  "Soy beans",
  "Canned raviolis",
  "Burger sauces",
  "Canola oils",
  "Basil",
  "Vegan patties",
  "Wines from Spain",
  "Fruit soy yogurts",
  "Ginger beer",
  "Devilled pork shoulder in mustard sauce",
  "Classic hummus",
  "Nonnettes",
  "Brioche filled with chocolate drops",
  "Fruit muffins",
  "Natural sugar substitutes",
  "Fresh ground beef steaks",
  "Filled chocolate eggs",
  "Grated coconut",
  "Sliced champignon mushrooms",
  "Crunchy almond turrón",
  "Caramel spreads",
  "Rooibos",
  "Canned lentils",
  "Refried beans",
  "Pepper sauces",
  "Thickeners",
  "Gizzards",
  "Canned white asparagus",
  "Andouillettes",
  "Roasted Cashew Nuts",
  "Beef cottage pies",
  "Molten chocolate cakes",
  "Frozen poultry",
  "Confiseries",
  "Candied fruits",
  "Extra fine dark chocolates",
  "Medjool dates",
  "Fresh carrots",
  "Chestnuts",
  "Brie de Meaux cheeses",
  "Linguine",
  "Lithuanian beers",
  "Spelt flours",
  "Maasdam",
  "Crunchy cereal clusters",
  "Turmeric powder",
  "Herbes de Provence",
  "From 12 months old",
  "Starches",
  "Cassoulets with duck confit",
  "Protein Energy Bars",
  "Zucchini",
  "Green tapenades",
  "Orecchiette",
  "Pumpkins and their products",
  "Canned white common beans",
  "Halloween foods and drinks",
  "Old style mustards",
  "Dark chocolates with orange",
  "French confectioneries",
  "Flammekueche",
  "Prosecco",
  "Vegan sauces",
  "Sugared popcorn",
  "Cornmeal",
  "Vegan creamy puddings",
  "Lemon sorbets",
  "White wheat flours",
  "Dried mangoes",
  "Samosas",
  "Shelled hazelnuts",
  "Goat milk yogurts",
  "Thyme honeys",
  "Buttermilks",
  "Sliced bacon",
  "Salmons from farming",
  "Frozen green beans",
  "Pancetta",
  "Carbonated fruit soft drink",
  "Brazil nuts",
  "Spätzle",
  "Fresh mixed vegetables",
  "Ravioles",
  "Botanas",
  "Sweet corn",
  "Green teas with mint",
  "Prepared meats with less salt",
  "Parma ham",
  "Energy drink without sugar and with artificial sweeteners",
  "Sausages from Spain",
  "Medium grain rices",
  "Coconut sugar",
  "Vegetarian hamburgers",
  "From 4 months",
  "Bran",
  "Tomme des Pyrénées",
  "Red wine vinegars",
  "Blinis",
  "Cereals for babies",
  "Milk chocolates with almonds",
  "Baker's yeast",
  "Legume flours",
  "Assortments of biscuits",
  "Poultry broth",
  "Half milk and half cream",
  "Digestives covered with chocolate",
  "Ossau-Iraty cheeses",
  "Fresh ground meat preparations",
  "Ground black peppers",
  "Crêpes de froment",
  "Tomato pulps",
  "Buckwheat flours",
  "Mango nectars",
]
